[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.8"
py-cord = "^2.4.1"
python-dotenv = "^1.0.0"
requests = "^2.31.0"

[tool.poetry.group.dev.dependencies]
icecream = "^2.0.0"
